# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
# apps/frontend/config/app.yml
all:
  active_days: 30
  max_jobs_on_homepage: 10